server:
  port: 8081

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/vue_backend?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: rhrnfu705

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      show_sql: true
